version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "9086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana-jh
    ports:
      - "3100:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    networks:
      - monitoring
    volumes:
      - grafana-data-jh:/var/lib/grafana

  k6:
    image: grafana/k6
    container_name: k6-jh
    depends_on:
      - influxdb
    volumes:
      - ./k6-scripts:/k6-scripts
    command: [ "run", "/k6-scripts/stress.js", "--out", "influxdb=http://influxdb:8086/k6" ]
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data-jh: