version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: uiverse-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./init/db:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  esdata:
    driver: local


