name: Deploy to AWS EB - docker

on:
  push:
    branches:
      - be/feat/222
#    types:
#      - closed
    # 해당 파일 또는 폴더 하위 파일들이 변경되었을 때에만!!!
    paths:
      - backend/log/src/**
      - build.gradle
      - .github/workflows/deploy-log.yml
      - .ebextensions/**
      - .platform/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_KEY }}
          submodules: true  # 서브모듈도 함께 가져옴
      - name: Pemission
        working-directory: backend/log
        run: chmod +x ./gradlew

      - name: Build with Gradle
        working-directory: backend/log
        run: ./gradlew clean build -x test
      # UTC가 기준이기 때문에 한국시간으로 맞추려면 +9시간 해야 한다
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"
      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"

      - name: Docker build
        working-directory: backend/log
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t log-cicd .
          docker tag log-cicd ${{ secrets.DOCKERHUB_USERNAME }}/log-cicd:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/log-cicd:latest

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ora-log-eb# 엘리스틱 빈스톡 애플리케이션 이름!
          environment_name: Ora-log-eb-env # 엘리스틱 빈스톡 환경 이름!
          version_label: blog-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: Dockerrun.aws.json